% Create a pifa antenna
% Generated by MATLAB(R) 9.10 and Antenna Toolbox 5.0.
% Generated on: 17-Dec-2021 17:21:41

%% Antenna Properties 
lambda = 0.1111;

antennaObject = design(pifa, 2700*1e6);
antennaObject.Length = 0.0258;
antennaObject.Width = 0.0335;
antennaObject.Height = 0.0016;
antennaObject.Substrate.Name = 'FR4';
antennaObject.Substrate.EpsilonR = 4.4;
antennaObject.Substrate.LossTangent = 0.026;
antennaObject.Substrate.Thickness = 0.0016;
antennaObject.GroundPlaneLength = 0.0258;
antennaObject.GroundPlaneWidth = 0.0335;
antennaObject.FeedOffset = [0.0087, 0];
% Show
% figure;
% show(antennaObject) 

%% Antenna Analysis 
% % Define plot frequency 
% plotFrequency = 2.7*1e9;
% % Define frequency range 
% freqRange = (2430:27:2970)*1e6;
% % pattern
% figure;
% pattern(antennaObject, plotFrequency)
% % current
% figure;
% current(antennaObject, plotFrequency)

%% Antenna Refinement


for i = 20:90
meshData = mesh (antennaObject,'MaxEdgeLength',lambda/(i));
%returnLoss(antennaObject,[2430e6:27e6:2970e6])
s=sparameters(antennaObject,[2430e6:27e6:2970e6]);
%rfplot(s);
eta_R(i)=20*log10(abs(s.Parameters(2)));
count = i
end

plot(abs(eta_R));
grid on;